=== Sharibo-EPAM-BelSUT-Training/task07_1/src/gmail/alexejkrawez/Medicine.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="Medicine"
	xmlns:m="Medicine" elementFormDefault="qualified">

	<!--
		xmlns="http://www.w3.org/2001/XMLSchema" задает пространство имен по
		умолчанию для элементов, атрибутов и типов схемы, которые принадлежат пространству
		имен "http://www.w3.org/2001/XMLSchema" и описаны соответствующей схемой.

		targetNamespace="http://www.example.com/Students" задает пространство имен
		для элементов/атрибутов, которые описывает данная схема

		xmlns:m="http://www.example.com/Students"
		вводит префикс для пространства имен (элементов) данной схемы. То есть для
		всех элементов, типов, описанных данной схемой и используемых здесь же требуется
		использовать префикс m, как в случае с типами – m:Address, m:Login
		и т.д.
	-->

	<element name="medicine">
		<complexType>
			<sequence>

				<element name="name" type="m:string"/>
                <element name="pharm" type="m:string"/>
                <element name="group" type="m:string"/>
                <element name="analogs" type="m:string" minOccurs="0" maxOccurs="unbounded"/>
                <element name="versions">
                    <complexType>
                        <sequence>
                            <element name="version" type="m:string"/>
                            <element name="certificate" type="m:string"/>
                            <element name="package" type="m:string"/>
                            <element name="dosage" type="m:string" minOccurs="1" maxOccurs="unbounded"/>
                        </sequence>
                    </complexType>
                </element>

			</sequence>
		</complexType>
	</element>

    <simpleType name="string">
        <restriction base="string"/>
    </simpleType>

</schema>

=== Sharibo-EPAM-BelSUT-Training/task07_1/out/production/task07_1/gmail/alexejkrawez/Medicine.xml
<?xml version="1.0" encoding="UTF-8"?>

<m:medicine
    xmlns:m="Medicine"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="Medicine
	Medicine.xsd">
        <m:name>Ацикловир</m:name>
        <m:pharm>АО «АВВА РУС»</m:pharm>
        <m:group>Противовирусные (за исключением ВИЧ) средства</m:group>
        <m:analogs>Зовиракс</m:analogs>
        <m:analogs>Ацикловир Сандоз</m:analogs>
        <m:versions>
            <m:version>Таблетки 200 мг</m:version>
            <m:certificate>№ ЛС-001205, 2011-07-15 от АВВА-РУС АО (Россия)</m:certificate>
            <m:package>Упаковка контурная ячейковая 10, пачка картонная 1</m:package>
            <m:dosage>Взрослые: 1 табл. (200 мг) внутрь 5 раз в день, 5 дней.
                Дети старше 2 лет: 1 табл. (200 мг) внутрь 5 раз в день, 5 дней.
                Дети младше 2 лет: — 0,5 табл. (100 мг) внутрь 5 раз в день, 5 дней.
            </m:dosage>
        </m:versions>
</m:medicine>
